#!/usr/bin/env python3
"""
OpenWandb Demo — MNIST Handwritten Digit Classification (Pure NumPy)
=====================================================================

Zero PyTorch / Zero Lightning — 100% NumPy from scratch, showcasing:
  - Hand-written MLP: Linear layers, ReLU/Tanh/LeakyReLU activations
  - Backpropagation: manual gradient computation through every layer
  - Adam optimizer: implemented from scratch (m, v, bias-correction)
  - Cosine annealing LR schedule
  - wandb.init()     — project, config, tags, notes, group, job_type
  - wandb.config     — hyperparameters (lr, hidden_sizes, activation, ...)
  - wandb.log()      — train/loss, train/acc, val/loss, val/acc, learning_rate
  - wandb.Image      — prediction samples with captions (true vs predicted)
  - wandb.Table      — prediction results table
  - wandb.Artifact   — model weight versioning (.npz)
  - wandb.summary    — best_val_acc, best_epoch, training_time
  - Namespace grouping — train/*, val/* auto-grouped in UI
  - Multi-run comparison — different architectures side-by-side

Dataset: Bundled MNIST subset (10K train + 2K test, shipped with openwandb)
Model:   NumPy MLP with configurable depth and activation

Requirements: pip install numpy wandb   (that's it!)

Usage:
    python openwandb-demo.py

Generated by: openwandb demo
"""

import os
import sys
import time
import math

# ================================================================
# Config (editable)
# ================================================================

SERVER_URL = os.environ.get("WANDB_BASE_URL", "{server_url}")
API_KEY = os.environ.get("WANDB_API_KEY", "{api_key}")
PROJECT = "{project}"
NUM_RUNS = {num_runs}
EPOCHS = {epochs}


# ================================================================
# Dependency checks
# ================================================================

def _check_deps():
    missing = []
    try:
        import numpy  # noqa: F401
    except ImportError:
        missing.append("numpy")
    try:
        import wandb  # noqa: F401
    except ImportError:
        missing.append("wandb")
    if missing:
        print("ERROR: missing packages: %s" % ", ".join(missing))
        print("  pip install %s" % " ".join(missing))
        sys.exit(1)

_check_deps()

import numpy as np
import wandb

# MNIST data from bundled package
from openwandb.mnist_data import load_mnist


# ================================================================
# 1. Layers — forward & backward (pure NumPy)
# ================================================================

class Linear:
    """Fully connected layer: y = x @ W + b"""

    def __init__(self, in_dim, out_dim):
        # He initialization
        self.W = np.random.randn(in_dim, out_dim).astype(np.float32) * np.sqrt(2.0 / in_dim)
        self.b = np.zeros(out_dim, dtype=np.float32)
        self.dW = None
        self.db = None
        self._x = None

    def forward(self, x):
        self._x = x
        return x @ self.W + self.b

    def backward(self, dout):
        self.dW = self._x.T @ dout
        self.db = dout.sum(axis=0)
        return dout @ self.W.T

    @property
    def num_params(self):
        return self.W.size + self.b.size


class ReLU:
    """ReLU activation: max(0, x)"""
    def forward(self, x):
        self._mask = (x > 0).astype(np.float32)
        return x * self._mask

    def backward(self, dout):
        return dout * self._mask


class Tanh:
    """Tanh activation"""
    def forward(self, x):
        self._out = np.tanh(x)
        return self._out

    def backward(self, dout):
        return dout * (1.0 - self._out ** 2)


class LeakyReLU:
    """Leaky ReLU activation: x if x>0 else alpha*x"""
    def __init__(self, alpha=0.01):
        self.alpha = alpha

    def forward(self, x):
        self._pos = (x > 0).astype(np.float32)
        return x * self._pos + self.alpha * x * (1.0 - self._pos)

    def backward(self, dout):
        return dout * (self._pos + self.alpha * (1.0 - self._pos))


# ================================================================
# 2. Loss — Softmax + Cross-Entropy
# ================================================================

def softmax(logits):
    """Numerically stable softmax."""
    e = np.exp(logits - logits.max(axis=1, keepdims=True))
    return e / e.sum(axis=1, keepdims=True)


def cross_entropy_loss(logits, labels):
    """Cross-entropy loss with softmax.

    Returns:
        loss (float): mean cross-entropy loss
        dlogits (ndarray): gradient w.r.t. logits
    """
    N = labels.shape[0]
    probs = softmax(logits)
    loss = -np.log(probs[np.arange(N), labels] + 1e-8).mean()
    dlogits = probs.copy()
    dlogits[np.arange(N), labels] -= 1.0
    dlogits /= N
    return loss, dlogits


# ================================================================
# 3. Adam Optimizer (from scratch)
# ================================================================

class Adam:
    """Adam optimizer — hand-written, no frameworks."""

    def __init__(self, linear_layers, lr=0.001, beta1=0.9, beta2=0.999, eps=1e-8):
        self.layers = linear_layers
        self.lr = lr
        self.base_lr = lr
        self.beta1 = beta1
        self.beta2 = beta2
        self.eps = eps
        self.t = 0
        # Per-parameter first & second moments
        self.states = []
        for layer in self.layers:
            self.states.append({
                "mW": np.zeros_like(layer.W),
                "vW": np.zeros_like(layer.W),
                "mb": np.zeros_like(layer.b),
                "vb": np.zeros_like(layer.b),
            })

    def step(self):
        self.t += 1
        bc1 = 1.0 - self.beta1 ** self.t
        bc2 = 1.0 - self.beta2 ** self.t

        for layer, state in zip(self.layers, self.states):
            # Update W
            state["mW"] = self.beta1 * state["mW"] + (1 - self.beta1) * layer.dW
            state["vW"] = self.beta2 * state["vW"] + (1 - self.beta2) * (layer.dW ** 2)
            mW_hat = state["mW"] / bc1
            vW_hat = state["vW"] / bc2
            layer.W -= self.lr * mW_hat / (np.sqrt(vW_hat) + self.eps)

            # Update b
            state["mb"] = self.beta1 * state["mb"] + (1 - self.beta1) * layer.db
            state["vb"] = self.beta2 * state["vb"] + (1 - self.beta2) * (layer.db ** 2)
            mb_hat = state["mb"] / bc1
            vb_hat = state["vb"] / bc2
            layer.b -= self.lr * mb_hat / (np.sqrt(vb_hat) + self.eps)


def cosine_annealing_lr(optimizer, epoch, total_epochs):
    """Cosine annealing LR schedule."""
    optimizer.lr = optimizer.base_lr * 0.5 * (1 + math.cos(math.pi * epoch / total_epochs))
    return optimizer.lr


# ================================================================
# 4. MLP Model (pure NumPy)
# ================================================================

class NumpyMLP:
    """Multi-Layer Perceptron — 100% NumPy, zero frameworks."""

    def __init__(self, hidden_sizes=(128, 64), activation="relu"):
        act_map = {"relu": ReLU, "tanh": Tanh, "leaky_relu": LeakyReLU}
        act_cls = act_map.get(activation, ReLU)

        self.layers = []          # all layers (Linear + Activation)
        self.linear_layers = []   # only Linear layers (for optimizer)

        in_dim = 784
        for h in hidden_sizes:
            linear = Linear(in_dim, h)
            self.layers.append(linear)
            self.linear_layers.append(linear)
            self.layers.append(act_cls())
            in_dim = h

        # Output layer (no activation — logits)
        output = Linear(in_dim, 10)
        self.layers.append(output)
        self.linear_layers.append(output)

    def forward(self, x):
        """Forward pass through all layers."""
        out = x
        for layer in self.layers:
            out = layer.forward(out)
        return out

    def backward(self, dout):
        """Backward pass — propagate gradients through all layers in reverse."""
        for layer in reversed(self.layers):
            dout = layer.backward(dout)

    @property
    def total_params(self):
        return sum(l.num_params for l in self.linear_layers)

    def get_weights(self):
        """Export all weights as a dict (for saving)."""
        weights = {}
        for i, layer in enumerate(self.linear_layers):
            weights["W%d" % i] = layer.W.copy()
            weights["b%d" % i] = layer.b.copy()
        return weights


# ================================================================
# 5. Training loop
# ================================================================

def make_batches(x, y, batch_size, shuffle=True):
    """Yield mini-batches from data."""
    N = x.shape[0]
    idx = np.arange(N)
    if shuffle:
        np.random.shuffle(idx)
    for start in range(0, N, batch_size):
        end = min(start + batch_size, N)
        batch_idx = idx[start:end]
        yield x[batch_idx], y[batch_idx]


def evaluate(model, val_x, val_y, batch_size=256):
    """Compute val loss and accuracy."""
    total_loss = 0.0
    correct = 0
    total = 0
    for bx, by in make_batches(val_x, val_y, batch_size, shuffle=False):
        logits = model.forward(bx)
        loss, _ = cross_entropy_loss(logits, by)
        total_loss += loss * by.shape[0]
        correct += (logits.argmax(axis=1) == by).sum()
        total += by.shape[0]
    return total_loss / total, correct / total


def train_one_run(config, project_name, group_name, run_idx, total_runs,
                  train_x, train_y, val_x, val_y, raw_val_images):
    """Train a single model run with full wandb integration."""

    name = config["name"]
    print("\n[Run %d/%d] %s (hidden=%s, lr=%s, act=%s)" % (
        run_idx, total_runs, name, config["hidden_sizes"],
        config["lr"], config["activation"]))
    print("-" * 60)

    os.environ["WANDB_BASE_URL"] = SERVER_URL
    os.environ["WANDB_API_KEY"] = API_KEY

    # --- wandb.init ---
    run = wandb.init(
        project=project_name,
        name=name,
        group=group_name,
        job_type="train",
        tags=config["tags"],
        notes=config["notes"],
        config=config,
    )

    epochs = config["epochs"]

    # --- Build model ---
    np.random.seed(42 + run_idx)
    model = NumpyMLP(
        hidden_sizes=config["hidden_sizes"],
        activation=config["activation"],
    )
    optimizer = Adam(model.linear_layers, lr=config["lr"])

    # --- Training ---
    t0 = time.time()
    best_val_acc = 0.0
    best_epoch = 0
    log_images_every = max(1, epochs // 5)

    for epoch in range(epochs):
        # Cosine annealing LR
        current_lr = cosine_annealing_lr(optimizer, epoch, epochs)

        # --- Train epoch ---
        train_loss_sum = 0.0
        train_correct = 0
        train_total = 0

        for bx, by in make_batches(train_x, train_y, config["batch_size"], shuffle=True):
            # Forward
            logits = model.forward(bx)
            loss, dlogits = cross_entropy_loss(logits, by)

            # Backward
            model.backward(dlogits)

            # Update
            optimizer.step()

            train_loss_sum += loss * by.shape[0]
            train_correct += (logits.argmax(axis=1) == by).sum()
            train_total += by.shape[0]

        train_loss = train_loss_sum / train_total
        train_acc = train_correct / train_total
        val_loss, val_acc = evaluate(model, val_x, val_y)

        # --- wandb.log ---
        log_dict = {
            "epoch": epoch,
            "train/loss": float(train_loss),
            "train/accuracy": float(train_acc),
            "val/loss": float(val_loss),
            "val/accuracy": float(val_acc),
            "learning_rate": float(current_lr),
        }

        # --- wandb.Image: prediction samples ---
        if epoch % log_images_every == 0 or epoch == epochs - 1:
            sample_x = val_x[:16]
            sample_logits = model.forward(sample_x)
            preds = sample_logits.argmax(axis=1)
            probs = softmax(sample_logits)
            confs = probs.max(axis=1)

            wandb_images = []
            for i in range(16):
                raw = raw_val_images[i]
                true_lbl = int(val_y[i])
                pred_lbl = int(preds[i])
                conf = float(confs[i])
                mark = "OK" if true_lbl == pred_lbl else "WRONG"
                caption = "true=%d pred=%d (%.0f%%) %s" % (true_lbl, pred_lbl, conf * 100, mark)
                wandb_images.append(wandb.Image(raw, caption=caption, mode="L"))
            log_dict["predictions"] = wandb_images

        wandb.log(log_dict)

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_epoch = epoch

        if epoch % 10 == 0 or epoch == epochs - 1:
            print("  Epoch %3d/%d | train_loss=%.4f train_acc=%.3f "
                  "| val_loss=%.4f val_acc=%.3f | lr=%.6f" % (
                      epoch + 1, epochs, train_loss, train_acc,
                      val_loss, val_acc, current_lr))

    training_time = time.time() - t0

    # --- wandb.summary ---
    wandb.summary["best_val_acc"] = float(best_val_acc)
    wandb.summary["best_val_loss"] = float(val_loss)
    wandb.summary["best_epoch"] = int(best_epoch)
    wandb.summary["training_time_sec"] = round(training_time, 2)
    wandb.summary["total_params"] = model.total_params

    print("  Done in %.1fs | best_val_acc=%.3f (epoch %d) | %d params" % (
        training_time, best_val_acc, best_epoch, model.total_params))

    # --- wandb.Table: prediction results ---
    try:
        logits = model.forward(val_x[:100])
        preds = logits.argmax(axis=1)
        probs = softmax(logits)
        confs = probs.max(axis=1)

        columns = ["image", "true", "predicted", "confidence", "correct"]
        table = wandb.Table(columns=columns)
        for i in range(100):
            img = wandb.Image(raw_val_images[i], mode="L")
            table.add_data(
                img,
                int(val_y[i]),
                int(preds[i]),
                round(float(confs[i]), 4),
                int(preds[i]) == int(val_y[i]),
            )
        wandb.log({"prediction_table": table})
        print("  Logged prediction table (100 samples)")
    except Exception as e:
        print("  Table logging skipped: %s" % e)

    # --- wandb.Artifact: model weights (.npz) ---
    try:
        weights_path = "model_%s.npz" % name
        np.savez(weights_path, **model.get_weights())
        artifact = wandb.Artifact(
            name="model-%s" % name,
            type="model",
            description="MNIST MLP %s (val_acc=%.3f) [pure NumPy]" % (name, best_val_acc),
            metadata={
                "architecture": str(config["hidden_sizes"]),
                "activation": config["activation"],
                "total_params": model.total_params,
                "framework": "numpy",
            },
        )
        artifact.add_file(weights_path)
        run.log_artifact(artifact)
        print("  Logged artifact: model-%s" % name)
        try:
            os.remove(weights_path)
        except OSError:
            pass
    except Exception as e:
        print("  Artifact logging skipped: %s" % e)

    wandb.finish()


# ================================================================
# 6. Run configs
# ================================================================

def get_run_configs(num_runs, epochs):
    all_configs = [
        {
            "name": "small-fast",
            "hidden_sizes": [64],
            "lr": 0.01,
            "batch_size": 128,
            "activation": "relu",
            "tags": ["demo", "mnist", "small", "numpy"],
            "notes": "Minimal MLP: single hidden layer 64 units. "
                     "Fast training, baseline for comparison. [pure NumPy]",
        },
        {
            "name": "medium-balanced",
            "hidden_sizes": [128, 64],
            "lr": 0.005,
            "batch_size": 64,
            "activation": "relu",
            "tags": ["demo", "mnist", "medium", "numpy"],
            "notes": "Two hidden layers [128, 64] with moderate learning rate. "
                     "Good balance between capacity and convergence speed. [pure NumPy]",
        },
        {
            "name": "large-deep",
            "hidden_sizes": [256, 128, 64],
            "lr": 0.001,
            "batch_size": 32,
            "activation": "leaky_relu",
            "tags": ["demo", "mnist", "large", "deep", "numpy"],
            "notes": "Deep 3-layer MLP [256, 128, 64] with LeakyReLU. "
                     "Higher capacity, slower convergence, should achieve best accuracy. [pure NumPy]",
        },
        {
            "name": "tanh-wide",
            "hidden_sizes": [256],
            "lr": 0.003,
            "batch_size": 64,
            "activation": "tanh",
            "tags": ["demo", "mnist", "wide", "tanh", "numpy"],
            "notes": "Wide single-layer with Tanh activation. "
                     "Compare Tanh vs ReLU on digit classification. [pure NumPy]",
        },
        {
            "name": "tiny-underfitting",
            "hidden_sizes": [16],
            "lr": 0.01,
            "batch_size": 128,
            "activation": "relu",
            "tags": ["demo", "mnist", "tiny", "underfitting", "numpy"],
            "notes": "Intentionally small (16 hidden units) to demonstrate underfitting. "
                     "Useful for showing model capacity vs performance trade-off. [pure NumPy]",
        },
    ]

    configs = all_configs[:num_runs]
    for cfg in configs:
        cfg["epochs"] = epochs
    return configs


# ================================================================
# 7. Main
# ================================================================

def main():
    os.environ.setdefault("WANDB_BASE_URL", SERVER_URL)
    os.environ.setdefault("WANDB_API_KEY", API_KEY)

    group_name = "mnist-demo-%s" % time.strftime("%Y%m%d-%H%M%S")

    # --- Load MNIST ---
    print("\nLoading MNIST data...")
    train_images, train_labels, test_images, test_labels = load_mnist()
    print("  Train: %d images, Test: %d images" % (len(train_images), len(test_images)))

    # Prepare float32 arrays — flatten to (N, 784) and normalize
    train_x = train_images.reshape(-1, 784).astype(np.float32) / 255.0
    train_y = train_labels.astype(np.int64)
    val_x = test_images.reshape(-1, 784).astype(np.float32) / 255.0
    val_y = test_labels.astype(np.int64)

    print()
    print("=" * 60)
    print("  OpenWandb Demo - MNIST Digit Classification")
    print("  Pure NumPy — zero PyTorch, zero frameworks")
    print("=" * 60)
    print("  Server:     %s" % SERVER_URL)
    print("  Project:    %s" % PROJECT)
    print("  Runs:       %d" % NUM_RUNS)
    print("  Epochs:     %d" % EPOCHS)
    print("  Group:      %s" % group_name)
    print("  Dataset:    %d train / %d test" % (len(train_images), len(test_images)))
    print("  Framework:  NumPy %s (no torch!)" % np.__version__)
    print("  Features:   wandb.log, wandb.Image, wandb.Table, wandb.Artifact")
    print("=" * 60)

    configs = get_run_configs(NUM_RUNS, EPOCHS)
    t_start = time.time()

    for idx, cfg in enumerate(configs, 1):
        train_one_run(
            cfg, PROJECT, group_name, idx, len(configs),
            train_x, train_y, val_x, val_y,
            test_images,  # raw uint8 for wandb.Image
        )

    total_time = time.time() - t_start

    print()
    print("=" * 60)
    print("  Demo complete! (%.1fs total)" % total_time)
    print()
    print("  Open your browser:")
    print("    Dashboard:  %s" % SERVER_URL)
    print("    Project:    %s/projects/default/%s" % (SERVER_URL, PROJECT))
    print()
    print("  What to explore:")
    print("    - Charts tab:  loss & accuracy curves")
    print("    - Media tab:   prediction images with labels")
    print("    - Config tab:  hyperparameter comparison")
    print("    - Compare all runs side-by-side")
    print()
    print("  Re-run:  python openwandb-demo.py")
    print("=" * 60)
    print()


if __name__ == "__main__":
    main()
