#!/usr/bin/env python3
"""
OpenWandb Demo — MNIST Handwritten Digit Classification
========================================================

PyTorch Lightning + wandb SDK, showcasing:
  - wandb.init()     — project, config, tags, notes, group, job_type
  - wandb.config     — hyperparameters (lr, hidden_sizes, activation, ...)
  - wandb.log()      — train/loss, train/acc, val/loss, val/acc, learning_rate
  - wandb.Image      — prediction samples with captions (true vs predicted)
  - wandb.Table      — prediction results table
  - wandb.Artifact   — model weights versioning
  - wandb.summary    — best_val_acc, best_epoch, training_time
  - Namespace grouping — train/*, val/* auto-grouped in UI
  - Multi-run comparison — different architectures side-by-side

Dataset: Bundled MNIST subset (10K train + 2K test, shipped with openwandb)
Model:   PyTorch MLP with configurable depth and activation

Usage:
    python openwandb-demo.py

Generated by: openwandb demo
"""

import os
import sys
import time

# ================================================================
# Config (editable)
# ================================================================

SERVER_URL = os.environ.get("WANDB_BASE_URL", "{server_url}")
API_KEY = os.environ.get("WANDB_API_KEY", "{api_key}")
PROJECT = "{project}"
NUM_RUNS = {num_runs}
EPOCHS = {epochs}


# ================================================================
# Dependency checks
# ================================================================

def _check_deps():
    missing = []
    try:
        import torch  # noqa: F401
    except ImportError:
        missing.append("torch")

    # Try lightning (2.0+) then pytorch_lightning (1.x)
    try:
        import lightning  # noqa: F401
    except ImportError:
        try:
            import pytorch_lightning  # noqa: F401
        except ImportError:
            missing.append("lightning")

    try:
        import wandb  # noqa: F401
    except ImportError:
        missing.append("wandb")

    try:
        import numpy  # noqa: F401
    except ImportError:
        missing.append("numpy")

    if missing:
        print("ERROR: missing packages: %s" % ", ".join(missing))
        print("  pip install %s" % " ".join(missing))
        sys.exit(1)

_check_deps()

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
import wandb

# Lightning import: support both lightning>=2.0 and pytorch_lightning<2.0
try:
    import lightning as L
    from lightning.pytorch.loggers import WandbLogger
    from lightning.pytorch.callbacks import Callback
except ImportError:
    import pytorch_lightning as L
    from pytorch_lightning.loggers import WandbLogger
    from pytorch_lightning.callbacks import Callback

# MNIST data from bundled package
from openwandb.mnist_data import load_mnist


# ================================================================
# 1. Lightning Module — MLP Classifier
# ================================================================

class MNISTClassifier(L.LightningModule):
    """Simple MLP for MNIST digit classification."""

    def __init__(self, hidden_sizes=(128, 64), lr=0.01, activation="relu"):
        super().__init__()
        self.save_hyperparameters()
        self.lr = lr

        act_map = {"relu": nn.ReLU, "tanh": nn.Tanh, "leaky_relu": nn.LeakyReLU}
        act_cls = act_map.get(activation, nn.ReLU)

        layers = []
        in_dim = 784
        for h in hidden_sizes:
            layers += [nn.Linear(in_dim, h), act_cls()]
            in_dim = h
        layers.append(nn.Linear(in_dim, 10))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x.view(x.size(0), -1))

    def training_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        loss = F.cross_entropy(logits, y)
        acc = (logits.argmax(1) == y).float().mean()
        self.log("train/loss", loss, on_step=False, on_epoch=True, prog_bar=True)
        self.log("train/accuracy", acc, on_step=False, on_epoch=True, prog_bar=True)
        return loss

    def validation_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        loss = F.cross_entropy(logits, y)
        acc = (logits.argmax(1) == y).float().mean()
        self.log("val/loss", loss, on_step=False, on_epoch=True, prog_bar=True)
        self.log("val/accuracy", acc, on_step=False, on_epoch=True, prog_bar=True)

    def configure_optimizers(self):
        opt = torch.optim.Adam(self.parameters(), lr=self.lr)
        sch = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=self.trainer.max_epochs)
        return [opt], [sch]


# ================================================================
# 2. Callback — Log prediction images via wandb.Image
# ================================================================

class ImagePredictionLogger(Callback):
    """Log sample prediction images every N epochs."""

    def __init__(self, val_images, val_labels, raw_images, every_n_epochs=5, num_samples=16):
        super().__init__()
        self.val_images = val_images      # tensor (N, 1, 28, 28) normalized
        self.val_labels = val_labels      # tensor (N,)
        self.raw_images = raw_images      # numpy uint8 (N, 28, 28) for display
        self.every_n = every_n_epochs
        self.num = num_samples

    def on_validation_epoch_end(self, trainer, pl_module):
        epoch = trainer.current_epoch
        if epoch % self.every_n != 0 and epoch != trainer.max_epochs - 1:
            return

        imgs = self.val_images[:self.num].to(pl_module.device)
        labels = self.val_labels[:self.num]
        with torch.no_grad():
            logits = pl_module(imgs)
        preds = logits.argmax(1).cpu()
        confs = F.softmax(logits, dim=1).max(1).values.cpu()

        wandb_images = []
        for i in range(self.num):
            raw = self.raw_images[i]  # uint8 28x28
            true_lbl = labels[i].item()
            pred_lbl = preds[i].item()
            conf = confs[i].item()
            mark = "OK" if true_lbl == pred_lbl else "WRONG"
            caption = "true=%d pred=%d (%.0f%%) %s" % (true_lbl, pred_lbl, conf * 100, mark)
            wandb_images.append(wandb.Image(raw, caption=caption, mode="L"))

        trainer.logger.experiment.log({"predictions": wandb_images})


# ================================================================
# 3. Train one run
# ================================================================

def train_one_run(config, project_name, group_name, run_idx, total_runs,
                  train_x, train_y, val_x, val_y, raw_val_images):
    """Train a single model run with full wandb integration."""

    name = config["name"]
    print("\n[Run %d/%d] %s (hidden=%s, lr=%s, act=%s)" % (
        run_idx, total_runs, name, config["hidden_sizes"],
        config["lr"], config["activation"]))
    print("-" * 60)

    # --- wandb Logger ---
    os.environ["WANDB_BASE_URL"] = SERVER_URL
    os.environ["WANDB_API_KEY"] = API_KEY

    wandb_logger = WandbLogger(
        project=project_name,
        name=name,
        group=group_name,
        job_type="train",
        tags=config["tags"],
        notes=config["notes"],
        config=config,
    )

    # --- DataLoaders ---
    train_ds = TensorDataset(train_x, train_y)
    val_ds = TensorDataset(val_x, val_y)
    train_loader = DataLoader(train_ds, batch_size=config["batch_size"],
                              shuffle=True, num_workers=0)
    val_loader = DataLoader(val_ds, batch_size=256, num_workers=0)

    # --- Model ---
    model = MNISTClassifier(
        hidden_sizes=config["hidden_sizes"],
        lr=config["lr"],
        activation=config["activation"],
    )

    # --- Image prediction callback ---
    img_callback = ImagePredictionLogger(
        val_images=val_x[:16],
        val_labels=val_y[:16],
        raw_images=raw_val_images[:16],
        every_n_epochs=max(1, config["epochs"] // 5),
        num_samples=16,
    )

    # --- Train ---
    t0 = time.time()
    trainer = L.Trainer(
        max_epochs=config["epochs"],
        logger=wandb_logger,
        callbacks=[img_callback],
        enable_progress_bar=True,
        enable_checkpointing=False,
        accelerator="cpu",
        log_every_n_steps=1,
    )
    trainer.fit(model, train_loader, val_loader)
    training_time = time.time() - t0

    # --- wandb.summary ---
    metrics = trainer.callback_metrics
    wandb.summary["best_val_acc"] = metrics.get("val/accuracy", torch.tensor(0)).item()
    wandb.summary["best_val_loss"] = metrics.get("val/loss", torch.tensor(0)).item()
    wandb.summary["training_time_sec"] = round(training_time, 2)
    total_params = sum(p.numel() for p in model.parameters())
    wandb.summary["total_params"] = total_params

    print("  Done in %.1fs | val_acc=%.3f | %d params" % (
        training_time,
        metrics.get("val/accuracy", torch.tensor(0)).item(),
        total_params))

    # --- wandb.Table: prediction results ---
    try:
        model.eval()
        with torch.no_grad():
            logits = model(val_x[:100])
        preds = logits.argmax(1)
        confs = F.softmax(logits, dim=1).max(1).values

        columns = ["image", "true", "predicted", "confidence", "correct"]
        table = wandb.Table(columns=columns)
        for i in range(100):
            img = wandb.Image(raw_val_images[i], mode="L")
            table.add_data(
                img,
                int(val_y[i].item()),
                int(preds[i].item()),
                round(confs[i].item(), 4),
                preds[i].item() == val_y[i].item(),
            )
        wandb.log({"prediction_table": table})
        print("  Logged prediction table (100 samples)")
    except Exception as e:
        print("  Table logging skipped: %s" % e)

    # --- wandb.Artifact: model weights ---
    try:
        weights_path = "model_%s.pt" % name
        torch.save(model.state_dict(), weights_path)
        artifact = wandb.Artifact(
            name="model-%s" % name,
            type="model",
            description="MNIST MLP %s (val_acc=%.3f)" % (
                name, metrics.get("val/accuracy", torch.tensor(0)).item()),
            metadata={
                "architecture": str(config["hidden_sizes"]),
                "activation": config["activation"],
                "total_params": total_params,
            },
        )
        artifact.add_file(weights_path)
        wandb_logger.experiment.log_artifact(artifact)
        print("  Logged artifact: model-%s" % name)
        try:
            os.remove(weights_path)
        except OSError:
            pass
    except Exception as e:
        print("  Artifact logging skipped: %s" % e)

    wandb.finish()


# ================================================================
# 4. Run configs
# ================================================================

def get_run_configs(num_runs, epochs):
    all_configs = [
        {
            "name": "small-fast",
            "hidden_sizes": [64],
            "lr": 0.01,
            "batch_size": 128,
            "activation": "relu",
            "tags": ["demo", "mnist", "small"],
            "notes": "Minimal MLP: single hidden layer 64 units. "
                     "Fast training, baseline for comparison.",
        },
        {
            "name": "medium-balanced",
            "hidden_sizes": [128, 64],
            "lr": 0.005,
            "batch_size": 64,
            "activation": "relu",
            "tags": ["demo", "mnist", "medium"],
            "notes": "Two hidden layers [128, 64] with moderate learning rate. "
                     "Good balance between capacity and convergence speed.",
        },
        {
            "name": "large-deep",
            "hidden_sizes": [256, 128, 64],
            "lr": 0.001,
            "batch_size": 32,
            "activation": "leaky_relu",
            "tags": ["demo", "mnist", "large", "deep"],
            "notes": "Deep 3-layer MLP [256, 128, 64] with LeakyReLU. "
                     "Higher capacity, slower convergence, should achieve best accuracy.",
        },
        {
            "name": "tanh-wide",
            "hidden_sizes": [256],
            "lr": 0.003,
            "batch_size": 64,
            "activation": "tanh",
            "tags": ["demo", "mnist", "wide", "tanh"],
            "notes": "Wide single-layer with Tanh activation. "
                     "Compare Tanh vs ReLU on digit classification.",
        },
        {
            "name": "tiny-underfitting",
            "hidden_sizes": [16],
            "lr": 0.01,
            "batch_size": 128,
            "activation": "relu",
            "tags": ["demo", "mnist", "tiny", "underfitting"],
            "notes": "Intentionally small (16 hidden units) to demonstrate underfitting. "
                     "Useful for showing model capacity vs performance trade-off.",
        },
    ]

    configs = all_configs[:num_runs]
    for cfg in configs:
        cfg["epochs"] = epochs
    return configs


# ================================================================
# 5. Main
# ================================================================

def _check_server(url, timeout=5):
    """Check if the OpenWandb server is reachable. Exit early instead of SDK retry loop."""
    import urllib.request
    import urllib.error
    check_url = url.rstrip("/") + "/graphql"
    try:
        req = urllib.request.Request(check_url, method="GET")
        urllib.request.urlopen(req, timeout=timeout)
        return True
    except (urllib.error.URLError, urllib.error.HTTPError, OSError):
        return False


def main():
    os.environ.setdefault("WANDB_BASE_URL", SERVER_URL)
    os.environ.setdefault("WANDB_API_KEY", API_KEY)
    # Prevent SDK from retrying forever if server goes down mid-run
    os.environ.setdefault("WANDB_INIT_TIMEOUT", "30")

    # --- Server connectivity check ---
    print("\nChecking OpenWandb server at %s ..." % SERVER_URL)
    if not _check_server(SERVER_URL):
        print("\n  ERROR: Cannot connect to OpenWandb server at %s" % SERVER_URL)
        print()
        print("  Please make sure the server is running:")
        print("    openwandb serve")
        print()
        print("  Or specify a different server URL:")
        print("    export WANDB_BASE_URL=http://your-server:8080")
        print("    python openwandb-demo.py")
        print()
        sys.exit(1)
    print("  Server is reachable.")

    group_name = "mnist-demo-%s" % time.strftime("%Y%m%d-%H%M%S")

    # --- Load MNIST ---
    print("\nLoading MNIST data...")
    train_images, train_labels, test_images, test_labels = load_mnist()
    print("  Train: %d images, Test: %d images" % (len(train_images), len(test_images)))

    # Prepare tensors
    train_x = torch.FloatTensor(train_images.reshape(-1, 1, 28, 28)) / 255.0
    train_y = torch.LongTensor(train_labels.astype(int))
    val_x = torch.FloatTensor(test_images.reshape(-1, 1, 28, 28)) / 255.0
    val_y = torch.LongTensor(test_labels.astype(int))

    print()
    print("=" * 60)
    print("  OpenWandb Demo - MNIST Digit Classification")
    print("  PyTorch Lightning + wandb SDK")
    print("=" * 60)
    print("  Server:     %s" % SERVER_URL)
    print("  Project:    %s" % PROJECT)
    print("  Runs:       %d" % NUM_RUNS)
    print("  Epochs:     %d" % EPOCHS)
    print("  Group:      %s" % group_name)
    print("  Dataset:    %d train / %d test" % (len(train_images), len(test_images)))
    print("  Features:   wandb.log, wandb.Image, wandb.Table, wandb.Artifact")
    print("=" * 60)

    configs = get_run_configs(NUM_RUNS, EPOCHS)
    t_start = time.time()

    for idx, cfg in enumerate(configs, 1):
        train_one_run(
            cfg, PROJECT, group_name, idx, len(configs),
            train_x, train_y, val_x, val_y,
            test_images,  # raw uint8 for wandb.Image
        )

    total_time = time.time() - t_start

    print()
    print("=" * 60)
    print("  Demo complete! (%.1fs total)" % total_time)
    print()
    print("  Open your browser:")
    print("    Dashboard:  %s" % SERVER_URL)
    print("    Project:    %s/projects/default/%s" % (SERVER_URL, PROJECT))
    print()
    print("  What to explore:")
    print("    - Charts tab:  loss & accuracy curves")
    print("    - Media tab:   prediction images with labels")
    print("    - Config tab:  hyperparameter comparison")
    print("    - Compare all runs side-by-side")
    print()
    print("  Re-run:  python openwandb-demo.py")
    print("=" * 60)
    print()


if __name__ == "__main__":
    main()
